### ISSUE TITLE
`image` module is missing from crate docs

### ISSUE THREAD

**Issue by YgorSouza** [buntine/barcoders#38]
As the `image` feature is not enabled by default, the corresponding module is not included in the [docs](https://docs.rs/barcoders/2.0.0/barcoders/generators/index.html#modules). This can be solved by adding the following to Cargo.toml:

```toml
[package.metadata.docs.rs]
all-features = true
```

As documented in <https://docs.rs/about/metadata>.
